apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: istio-cni
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.28.3
  releaseName: istio/cni
  namespace: kube-system
  valuesFile: values.yaml
