apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kiali-operator
  repo: https://kiali.org/helm-charts
  version: 1.30.0
  releaseName: kiali-operator
  namespace: monitoring
  valuesInline:
    auth:
      strategy: anonymous
    deployment:
      ingress:
        class_name: traefik
        override_yaml:
          metadata:
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
