renovate:
  mendRnvAcceptTos: 'y'
  mendRnvPlatform: 'github'
  config: |
    module.exports = {
      "kubernetes": {
        "fileMatch": ["\\.yaml$"]
      }
    }
  existingSecret: renovate-secret
  mendRnvCronJobSchedulerAll: '0 * * * *'
ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    renovate.<path:secret/data/infra#domain>:
      paths:
      - path: '/'
        pathType: Prefix
resources:
  requests:
    cpu: 250m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 4Gi
nodeSelector:
  size: s
