apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
  namespace: monitoring
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: grafana-secret
  data:
  - secretKey: admin.passwordKey
    remoteRef:
      key: /monitoring/grafana
      property: adminPassword
