apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.28.3
  releaseName: istio/istiod
  namespace: network
  valuesFile: values.yaml
- name: ztunnel
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.28.3
  releaseName: istio/ztunnel
  namespace: network
  valuesFile: values.yaml
