pvc:
  storageClassName: nfs-sc
  accessModes:
  - ReadWriteOnce
  size: 10Gi

deployment:
  nodeSelector:
    size: m
  image:
    repository: docker.io/jellyfin/jellyfin
    tag: "10.11.6"
  replicas: 1

service:
  type: ClusterIP
  port: 8096

nfs: 192.168.10.100

backup:
  schedule: "0 15 * * *"
  image:
    repository: busybox
    tag: "1.37"
  command: |
    echo "Starting backup at $(date)"
    tar -czf /backup/jellyfin-$(date +%Y%m%d%H%M%S).tar.gz /config
    echo "Backup completed at $(date)"
    echo "Removing backups older than 3 days"
    find /backup -maxdepth 1 -mtime +3 -type f -delete

domain: <path:secret/data/infra#domain>
