apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-route
  namespace: monitoring
spec:
  parentRefs:
  - name: cluster-gateway
    namespace: network
    sectionName: https
  hostnames:
  - "prometheus.${INFRA_DOMAIN}"
  rules:
  - backendRefs:
    - name: prometheus-server
      port: 80
