apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: crowdsec
  repo: https://crowdsecurity.github.io/helm-charts
  version: 0.21.1
  releaseName: crowdsec
  namespace: monitoring
  valuesFile: values.yaml
